all: CP-PCD-PIV-144_Additional_Route_Values.docx \
    CP-PCD-145-MWP_PCDTF_ACM_Alert_Timing_Diagram_01.docx \
    CP-PCD-146-MWP_PCDTF_ACM_Alert_Fatigue_04.docx \
    CP-PCD-153_PCDTF_ACM_Change¬_PCD-05_PRT-9_from_O_or_C_to_CE_and_occurrences_to_0..104_20210507.docx \
    CP-PCD-154-MWP_PCDTF_ACM_AR_optional_PCD-05_filtering_01_002_Philips.docx \
    CP-PCD-155-IPEC_PUMP_Slots-Racks-Pillars_20210512r00.docx \
    CP-PCD-PIV-140_Update_to_PIV_-_TF_Vol_2_06-25-2019.docx \
    CP-PCD-PIV-141_Bolus_from_existing_infusion_06-25-2019.docx \
    CP-PCD-PIV-142_Multistep__06-25-2019.docx \
    CP-PCD-PIV-144_Additional_Route_Values.docx \
    CP-PCD-nnn-MWP_PCDTF_ACM_AR_optional_PCD-05_filtering_01_002.docx \
    CP-PCD-nnn-MWP_PCDTF_ACM_AR_optional_PCD-05_filtering_01_002_Philips.docx 

%.docx:%.doc
	textutil -convert docx $<
